# Site settings
name: Christopher Magana
email: cmagana.inbox@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Python, C++, Machine Learning, Deep Learning, Startups, Agile, Embedded Systems"
skills: "Software Engineer in Worcester, MA"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/cmaga/

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1

# Build settings
markdown: kramdown
permalink: pretty
